ARG CLIENT_PORT=3000
ARG NODE_VERSION=18

FROM node:$NODE_VERSION

WORKDIR /app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn lerna bootstrap && yarn build:client

EXPOSE $CLIENT_PORT

CMD [ "yarn", "run", "start:client" ]
