ARG CLIENT_PORT=3000
ARG NODE_VERSION=18

# Этап 1: Сборка приложения
FROM node:$NODE_VERSION AS build

WORKDIR /app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn lerna bootstrap && yarn build:client

# Этап 2: Конечный контейнер
FROM node:$NODE_VERSION

WORKDIR /app

COPY --from=build /app /app

EXPOSE $CLIENT_PORT

CMD [ "yarn", "run", "start:client" ]
