ARG SERVER_PORT=3001
ARG NODE_VERSION=18

FROM node:$NODE_VERSION

WORKDIR /app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn lerna bootstrap && yarn build:server

EXPOSE $SERVER_PORT

CMD [ "yarn", "run", "start:server" ]
