version: '3.9'

services:
  nginx:
    container_name: tanki-nginx
    image: tanki-nginx
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ssl:/ssl
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    networks:
      - tanki-net
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - client
      - server
      - postgres
      - pgadmin

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot

  client:
    container_name: tanki-client
    image: tanki-client
    restart: always
    command: yarn run start:client
    build:
      context: .
      dockerfile: ./Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    env_file:
      - .env
    networks:
      - tanki-net
    depends_on:
      - server

  server:
    container_name: tanki-server
    image: tanki-server
    restart: always
    command: yarn run start:server
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      NODE_ENV: development
    networks:
      - tanki-net
    depends_on:
      - postgres

  postgres:
    container_name: tanki-postgres
    image: postgres:15-alpine
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./tmp/pgdata/:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - tanki-net

  pgadmin:
    container_name: tanki-pgadmin
    image: dpage/pgadmin4
    restart: always
    user: root
    ports:
      - '${PGADMIN_LISTEN_PORT_OUTPUT}:${PGADMIN_LISTEN_PORT}'
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    volumes:
      - ./tmp/pgadmin/:/var/lib/pgadmin
    networks:
      - tanki-net
    depends_on:
      - postgres

networks:
  tanki-net:
    driver: bridge
