export enum ERoutes {
  INDEX = '/',
  LOGIN = 'login',
  PROFILE = 'profile',
  REGISTRATION = 'registration',
  GAME = 'game',
  LEADERBOARD = 'leaderboard',
  FORUM = 'forum',
  TOPIC = 'topic',
  ENDGAME = 'endgame',
  GAMETOSTART = 'loading',
  ERROR400 = 'error400',
  ERROR404 = 'error404',
  ERROR500 = 'error500',
}
