import { SceneBlockPositions } from '../types'

export const scenesConfig: Record<number, SceneBlockPositions> = {
  1: {
    brick: [
      { x: 0, y: 2 },
      { x: 0, y: 4 },
      { x: 0, y: 7 },
      { x: 0, y: 11 },
      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 1, y: 6 },
      { x: 1, y: 9 },
      { x: 1, y: 10 },
      { x: 2, y: 4 },
      { x: 3, y: 6 },
      { x: 3, y: 8 },
      { x: 3, y: 9 },
      { x: 3, y: 11 },
      { x: 4, y: 3 },
      { x: 4, y: 8 },
      { x: 4, y: 9 },
      { x: 4, y: 10 },
      { x: 5, y: 3 },
      { x: 5, y: 6 },
      { x: 5, y: 7 },
      { x: 5, y: 7 },
      { x: 5, y: 11 },
      { x: 5, y: 12 },
      { x: 6, y: 3 },
      { x: 6, y: 8 },
      { x: 6, y: 9 },
      { x: 6, y: 11 },
      { x: 7, y: 5 },
      { x: 7, y: 11 },
      { x: 7, y: 12 },
      { x: 7, y: 11 },
      { x: 8, y: 5 },
      { x: 8, y: 6 },
      { x: 8, y: 8 },
      { x: 8, y: 9 },
      { x: 9, y: 2 },
      { x: 9, y: 5 },
      { x: 9, y: 6 },
      { x: 9, y: 12 },
      { x: 10, y: 2 },
      { x: 10, y: 4 },
      { x: 10, y: 10 },
      { x: 11, y: 1 },
      { x: 11, y: 2 },
      { x: 11, y: 9 },
      { x: 11, y: 10 },
      { x: 12, y: 7 },
      { x: 12, y: 12 },
    ],
    eagle: { x: 6, y: 12 },
  },
}
